<?php

namespace AppBundle\Repository;

/**
 * SourceApiXRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceApiXRepository extends \Doctrine\ORM\EntityRepository
{
}
